# SPDX-FileCopyrightText: Copyright 2025 Siemens AG
# SPDX-License-Identifier: Apache-2.0
#
# The original code is from the cmp-test-suite project:
#   https://github.com/siemens/cmp-test-suite
#  Code owner: Alexandr Railean
# This code may be modified, or just copy pasted from the original.
#

# This builds on top of the base image, adding the dependencies that are only
# needed for quality tests (linting, formatting, type checking, etc.).
# By default it attempts to use the locally stored image, but you can also rely
# on an external image registry if you specify another base when building:
# `docker build --build-arg BASE_IMAGE=ghcr.io/${GITHUB_REPOSITORY_OWNER}/keyutils-base:latest -f data/dockerfiles/Dockerfile.dev .`
# To experiment locally, build it with:
# `docker build -t keyutils-dev -f data/dockerfiles/Dockerfile.dev .`

ARG BASE_IMAGE=keyutils-base:latest
FROM ${BASE_IMAGE}

WORKDIR /app

COPY pyproject.toml .
RUN uv sync --no-install-project --all-extras

# By default we just print some environment information, which might be useful
# for troubleshooting.
CMD ["sh", "-c", "uname -a && python3 --version && openssl version && pip3 freeze"]
